agentes_nocivos = {
    "Ruído": [
        "O agente ruído encontra previsão no código 1.1.6 do Quadro anexo ao Decreto nº 53.831/64, no código 1.1.5 do Anexo III do Decreto nº 83.080/79 e no código 2.0.1 do anexo IV dos Decretos 2.172/1997 e 3.048/1999.",
        "Em razão de mudanças na legislação e na linha seguida pela jurisprudência, o reconhecimento da especialidade do período pela exposição ao agente obedece à seguinte linha do tempo:",
        "-Até 05/03/1997- ruído acima de 80 decibéis;",
        "-Entre 06/03/1997 e 18/11/2003- ruído acima de 90 decibéis;",
        "-A partir de 19/11/2003- ruído acima de 85 decibéis.",
        "Sobre o tema, destaco as teses repetitivas do STJ:",
        "TEMA 694- O limite de tolerância para configuração da especialidade do tempo de serviço para o agente ruído deve ser de 90 dB no período de 6.3.1997 a 18.11.2003, conforme Anexo IV do Decreto 2.172/1997 e Anexo IV do Decreto 3.048/1999, sendo impossível aplicação retroativa do Decreto 4.882/2003, que reduziu o patamar para 85 dB, sob pena de ofensa ao art. 6º da LINDB (ex-LICC).",
        "TEMA 1083- O reconhecimento do exercício de atividade sob condições especiais pela exposição ao agente nocivo ruído, quando constatados diferentes níveis de efeitos sonoros, deve ser aferido por meio do Nível de Exposição Normalizado (NEN). Ausente essa informação, deverá ser adotado como critério o nível máximo de ruído (pico de ruído), desde que perícia técnica judicial comprove a habitualidade e a permanência da exposição ao agente nocivo na produção do bem ou na prestação do serviço."
    ],
    "Calor": [
        "O agente calor encontra previsão no código 1.1.1 do Quadro anexo ao Decreto nº 53.831/64 (Jornada normal em locais com TE acima de 28º), no código 1.1.1 do Anexo III do Decreto nº 83.080/79 (Jornada normal em locais com TE acima de 28º) e no código 2.0.4 do anexo IV dos Decretos 2.172/1997 e 3.048/1999 (trabalhos com exposição ao calor acima dos limites de tolerância estabelecidos na NR15)."
    ],
    "Eletricidade": [
        "O agente eletricidade está previsto no código 1.1.8 do Quadro anexo ao Decreto nº 53.831/64 e no código 1.1.8 do Anexo III do Decreto nº 83.080/79 (tensão superior a 250 volts).",
        "Não há previsão expressa ao agente nos Decretos 2.172/1997 e 3.048/1999. Contudo, a jurisprudência do STJ firmou tese repetitiva no sentido de que as listagens dos agentes nocivos são exemplificativas, conforme segue:",
        "TEMA 534- As normas regulamentadoras que estabelecem os casos de agentes e atividades nocivos à saúde do trabalhador são exemplificativas, podendo ser tido como distinto o labor que a técnica médica e a legislação correlata considerarem como prejudiciais ao obreiro, desde que o trabalho seja permanente, não ocasional, nem intermitente, em condições especiais (art. 57, § 3º, da Lei 8.213/1991).",
        "Na linha do entendimento da Corte Superior, a exposição ao agente eletricidade, desde que em tensão superior a 250 volts, continua a caracterizar o tempo como especial (vide REsp 1306113 / SC - S1 - PRIMEIRA SEÇÃO - DJe 07/03/2013)."
    ],
    "Hidrocarbonetos": [
        "Com relação aos hidrocarbonetos, é considerado especial o labor realizado pelo indivíduo que fica exposto, de forma habitual e permanente, ao agente, conforme estabelecido pelos códigos 1.2.9 e 1.2.11 do Quadro do Decreto nº 53.831/64, códigos 1.2.10 e 1.2.11 do Anexo III do Decreto nº 83.080/79 e pelos códigos 1.0.17 e 1.0.19 do anexo IV dos Decretos 2.172/1997 e 3.048/1999. Há que se destacar que a nafta possui hidrocarbonetos em sua composição.",
        "No que tange ao benzeno, hidrocarboneto aromático comprovadamente cancerígeno (anexo 13-A da NR 15), a exposição é considerada especial mediante análise qualitativa e independentemente da previsão de neutralização do agente pela utilização de EPI. Há expressa previsão do agente no código 1.2.11 do Quadro do Decreto nº 53.831/64, no código 1.2.10 do Anexo III do Decreto nº 83.080/79 e nos códigos 1.0.3 e 1.0.19 do Anexo IV dos Decretos 2.172/1997 e 3.048/99.",
        "Nesse sentido, a jurisprudência do TRF da 3ª Região:",
        "DIREITO PREVIDENCIÁRIO. APELAÇÃO CÍVEL. RECONHECIMENTO DE ATIVIDADE ESPECIAL. EXPOSIÇÃO A AGENTES NOCIVOS. HIDROCARBONETOS E BENZENO. USO DE EPI. APOSENTADORIA ESPECIAL CONCEDIDA. REEXAME NECESSÁRIO AFASTADO. RECURSO DESPROVIDO. I. CASO EM EXAME Apelação interposta pelo INSS contra sentença que reconheceu o direito de segurado à aposentadoria especial, com cômputo de tempo especial de 06/03/1997 a 30/06/2013, laborado junto à Petrobras, onde o segurado estava exposto a agentes nocivos (hidrocarbonetos e benzeno). A sentença determinou a concessão da aposentadoria especial desde a data do requerimento administrativo (28/08/2013). II. QUESTÃO EM DISCUSSÃO Há duas questões em discussão: (i) verificar se o tempo de serviço especial devido à exposição a agentes nocivos (hidrocarbonetos e benzeno) foi comprovado pelo segurado; (ii) determinar se o uso de Equipamentos de Proteção Individual (EPI) foi suficiente para neutralizar a nocividade desses agentes e afastar a concessão da aposentadoria especial. III. RAZÕES DE DECIDIR Nos termos do art. 496, §3º, I, do CPC/2015, a sentença não está sujeita a reexame necessário, pois o valor da condenação não ultrapassa mil salários mínimos. O tempo de serviço especial foi devidamente comprovado mediante a apresentação do Perfil Profissiográfico Previdenciário (PPP) e laudo técnico, que indicaram a exposição habitual e permanente a agentes nocivos, em especial benzeno e hidrocarbonetos. A jurisprudência consolidada (ARE 664335/STF) e as normas regulamentares (Anexo 13 da NR-15) estabelecem que, para agentes como benzeno, a simples exposição já caracteriza a insalubridade, sendo irrelevante a análise quantitativa ou o uso de EPI, que não neutraliza a nocividade desses agentes. A habitualidade e permanência da exposição foram comprovadas pelo PPP, sendo suficiente para o reconhecimento da atividade especial, conforme previsto no art. 65 do Regulamento da Previdência Social (RPS). O fornecimento de EPI, embora consignado no PPP, não demonstrou sua capacidade de neutralizar a nocividade do benzeno, conforme entendimento jurisprudencial. IV. DISPOSITIVO E TESE Recurso desprovido (TRF3 - 5015966-76.2021.4.03.6105 - 7ª Turma - Relator(a): Desembargador Federal LUCIANA ORTIZ TAVARES COSTA ZANONI - Julgamento: 14/11/2024 - DJEN Data: 21/11/2024)."
    ],
    "serralheiro_antes_1995": [
        "As funções de serralheiro e auxiliar de serralheiro são atividades análogas a de esmerilhador, porque há exposição a fumos metálicos e à solda, devendo ser reconhecida a natureza especial dos trabalhos desenvolvidos, por enquadramento no código 2.5.3 do Decreto nº 83.080/79 (Parecer da SSMT no processo MPAS n° 34.230/83).",
        "Há julgados do TRF da 3ª Região que reconhecem a natureza especial de labor na função de serralheiro, conforme segue:",
        "PREVIDENCIÁRIO. APOSENTADORIA POR TEMPO DE CONTRIBUIÇÃO. ATIVIDADE ESPECIAL. ENQUADRAMENTO DE CATEGORIA PROFISSIONAL. MECÂNICO. AGENTES QUÍMICOS HIDROCARBONETOS. RECONHECIMENTO. PREENCHIMENTO DOS REQUISITOS PARA CONCESSÃO DO BENEFÍCIO. TERMO INICIAL. DER. (...) 3. Até 28.4.1995, as atividades dos metalúrgicos podem ser enquadradas como especiais, por categoria profissional, com fundamento nos itens 2.5.2 (trabalhadores das indústrias metalúrgicas e mecânicas) e 2.5.3 (serralheiros e seus auxiliares) do Decreto n. 53.831/1964, bem como com base nos itens 2.5.1 (indústrias metalúrgicas e mecânicas), 2.5.2 (ferrarias, estamparias de metal a quente e caldeiraria) e 2.5.3 (operações diversas) do Decreto n. 83.080/1979 (TRF3 - 5001051-43.2023.4.03.6140 - ApCiv - APELAÇÃO CÍVEL - 10ª Turma - Relator(a): DESEMBARGADOR FEDERAL JOAO EDUARDO CONSOLIM - Julgamento: 26/03/2025 - DJEN Data: 31/03/2025)."
    ],
    "Esgoto": [
        "É especial o tempo de trabalho com exposição a agentes biológicos (esgoto), considerando a previsão no código 1.3.0 do quadro anexo ao Decreto n° 53.831/1964, no código 1.3.0 do anexo I do Decreto n° 83.080/1979, no código 3.0.0 do anexo IV do Decreto n° 2.172/1997 e no código 3.0.0 do anexo IV do Decreto n° 3.048/1999.",
        "Cabe consignar que a habitualidade, no ponto, é comprovada quando a exposição a agentes nocivos é inerente à atividade desenvolvida, sendo este o caso verificado. Assim vem entendendo o STJ, in verbis:",
        "PREVIDENCIÁRIO E PROCESSUAL CIVIL. NEGATIVA DE PRESTAÇÃO JURISDICIONAL. DEFICIÊNCIA DE FUNDAMENTAÇÃO. ÓBICE DA SÚMULA 284/STF. TEMPO ESPECIAL. EXPOSIÇÃO A AGENTES BIOLÓGICOS. AMBIENTE HOSPITALAR. CONCEITOS DE HABITUALIDADE E PERMANÊNCIA QUE COMPORTAM INTERPRETAÇÃO. PREVALÊNCIA DO CRITÉRIO QUALITATIVO. RISCO IMINENTE. AVALIAÇÃO DA REAL EFETIVIDADE E DA DEVIDA UTILIZAÇÃO DO EPI. REEXAME DE PROVA. SÚMULA 7/STJ. CONVERSÃO DE TEMPO DE SERVIÇO COMUM EM ESPECIAL. INCIDÊNCIA DA LEGISLAÇÃO VIGENTE QUANDO PREENCHIDOS OS REQUISITOS DO BENEFÍCIO PRETENDIDO. MATÉRIA JÁ DECIDIDA SOB O RITO DO ART. 543-C DO CPC. 1. É deficiente a fundamentação do recurso especial em que a alegação de ofensa ao art. 535 do CPC se faz de forma genérica, sem a demonstração exata dos pontos pelos quais o acórdão se fez omisso, contraditório ou obscuro. Aplica-se, na hipótese, o óbice da Súmula 284 do STF. 2. A circunstância de o contato com os agentes biológicos não perdurar durante toda a jornada de trabalho não significa que não tenha havido exposição a agentes nocivos de forma habitual e permanente, na medida que a natureza do trabalho desenvolvido pela autora, no ambiente laboral hospitalar, permite concluir por sua constante vulnerabilidade. Questão que se resolve pelo parâmetro qualitativo, e não quantitativo.3. Na hipótese, a instância ordinária manifestou-se no sentido de que, sendo evidente a exposição a agentes de natureza infecto-contagiosa, não há como atestar a real efetividade do Equipamento de Proteção Individual - EPI. Rever esse entendimento, tal como colocada a questão nas razões recursais, demandaria, necessariamente, novo exame do acervo fático-probatório constante dos autos, providência vedada em recurso especial, conforme o óbice da Súmula 7/STJ. 4. No julgamento do REsp 1.310.034/PR, Rel. Ministro HERMAN BENJAMIN, processado nos termos do arts. 543-C do CPC, o STJ firmou entendimento no sentido de que, para fazer jus à conversão de tempo de serviço comum em especial, é necessário que o segurado tenha reunido os requisitos para o benefício pretendido antes da vigência da Lei n. 9.032/95, independentemente do regime jurídico reinante à época em que prestado o serviço. 5. Recurso especial do INSS parcialmente provido, para se afastar a pretendida conversão de tempo de serviço comum em especial. (STJ - REsp 1468401 / RS - Ministro SÉRGIO KUKINA - T1 - PRIMEIRA TURMA - DJe 27/03/2017).",
        "Ressalte-se, ainda, que a exposição aos agentes biológicos é verificada em análise qualitativa, de forma que basta o contato físico para caracterização da especialidade do labor. Além disso, a utilização de equipamentos de proteção apenas é capaz de minimizar, mas não de eliminar o risco da exposição. Nesse sentido, o entendimento do TRF da 3ª Região:",
        "APELAÇÃO CÍVEL. DIREITO PREVIDENCIÁRIO. EFEITO SUSPENSIVO NEGADO. REEXAME NECESSÁRIO. NÃO CABIMENTO. TEMPO URBANO. SENTENÇA TRABALHISTA. TRABALHO EM CONDIÇÕES ESPECIAIS. ATIVIDADE DE ATENDENTE DE ENFERMAGEM. ENQUADRAMENTO POR CATEGORIA PROFISSIONAL. POSSIBILIDADE ATÉ 28/04/1995. BALCONISTA DE FARMÁCIA. EXPOSIÇÃO A AGENTE NOCIVO NÃO COMPROVADA. RUÍDO. QUÍMICOS. BIOLÓGICOS. HABITUALIDADE. EPI INEFICAZ. INDICADOR IEAN. PRESUNÇÃO DA ESPECIALIDADE DO VÍNCULO. TEMPO INSUFICIENTE PARA A CONCESSÃO DE APOSENTADORIA ESPECIAL. DIREITO À REVISÃO DO BENEFÍCIO DE APOSENTADORIA POR TEMPO DE CONTRIBUIÇÃO. PRESCRIÇÃO QUINQUENAL. NÃO OCORRÊNCIA. AUTODECLARAÇÃO. JUROS DE MORA E CORREÇÃO MONETÁRIA ALTERADOS DE OFÍCIO. HONORÁRIOS ADVOCATÍCIOS MANTIDOS. HONORÁRIOS RECURSAIS DEVIDOS PELO INSS. CUSTAS. PREQUESTIONAMENTO. APELAÇÃO DO INSS IMPROVIDA E DO AUTOR PROVIDA EM PARTE.(...)",
        "- Nesse ponto, vale dizer que, segundo o Anexo 14 da NR-15 do Ministério do Trabalho, a exposição do trabalhador a agentes biológicos tem sua intensidade medida a partir de análise qualitativa, bastando apenas o contato físico para caracterização da especialidade do labor. Assim, independentemente do PPP revelar a que concentração se deu a exposição, houve o contato habitual e permanente aos agentes biológicos. (...)",
        "- Quanto aos agentes químicos e biológicos, sabe-se que, mesmo havendo informação nesse sentido, a utilização de EPI não tem o condão de neutralizar o efeito dos agentes nocivos, embora possam minimizá-los. Dessa forma, por não haver prova nos autos da real neutralização ou atenuação do agente nocivo, não há que se falar em descaracterização da insalubridade.",
        "(5004716-46.2021.4.03.6105 - ApCiv - APELAÇÃO CÍVEL - 7ª Turma - Relator(a): Desembargador Federal INES VIRGINIA PRADO SOARES - Julgamento: 10/10/2024 - DJEN Data: 14/10/2024)"
    ]
}
